[data]
num_nodes = 2048
height = 32
width = 64
lag = 5
horizon = 4
val_ratio = 1
test_ratio = 1
tod = False
normalizer = std
column_wise = False
feature_wise = True

[model]
input_dim = 11
output_dim = 1
embed_dim = 32
hidden_dim = 96
alpha = 4
time_dependence = True
time_divided = False
model_type = Full
use_cnn_encoder = True
num_afno_blocks = 8
use_mcdp_net = True

[train]
loss_func = mse
seed = 1001
batch_size = 32
epochs = 300
lr_init = 0.001
lr_decay = True
lr_scheduler_type = cosine
lr_min = 1e-6
early_stop = False
early_stop_patience = 100
grad_norm = False
max_grad_norm = 5
real_value = False
warm_start = False
dropout_rate = 0.01
r_drop_beta = 7

[test]
mae_thresh = None
mape_thresh = 0.

[log]
log_step = 1
plot = True


[mcdp_params]
gcn_depth = 2
dropout = 0.3
alpha = 0.05
beta = 0.95
gamma = 0.95
node_dim = 40
hyperGNN_dim = 16
